name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20.9.0
      uses: actions/setup-node@v2
      with:
        node-version: 20.9.0
    - run: npm install
    - run: npm run dev
